Merging task.sh into task.yml

diff --git a/tasks/replicate-tile/task.yml b/tasks/replicate-tile/task.yml
--- a/tasks/replicate-tile/task.yml
+++ b/tasks/replicate-tile/task.yml
@@ -7,7 +7,6 @@ params:
   REPLICATED_NAME:
 
 inputs:
-- name: git-repo
 - name: product
 - name: replicator
 
@@ -15,4 +14,31 @@ outputs:
 - name: output-folder
 
 run:
-  path: git-repo/tasks/replicate-tile/task.sh
+  path: bash
+  args:
+  - "-c"
+  - |
+    if [[ $DEBUG == true ]]; then
+      set -ex
+    else
+      set -e
+    fi
+
+    REPLICATOR_CLI=$(find replicator/ -name "*linux")
+    chmod +x $REPLICATOR_CLI
+    CMD=./$REPLICATOR_CLI
+
+    INPUT_FILE=$(find product/ -name "*.pivotal")
+    FILE_NAME=$(echo $INPUT_FILE | cut -d '/' -f2)
+    OUTPUT_FILE=output-folder/$FILE_NAME
+
+    if [[ ! -z "$REPLICATED_NAME" ]]; then
+      echo "Replicating the tile and adding " $REPLICATED_NAME
+      $CMD -name $REPLICATED_NAME -path $INPUT_FILE -output $OUTPUT_FILE
+    else
+      echo "Replication of the tile is not required " $REPLICATOR_NAME
+      mv $INPUT_FILE $OUTPUT_FILE
+    fi
+
+    cp product/metadata.* output-folder/
+    cp product/version output-folder/
